In [1]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

df = pd.read_csv('googleplaystore.csv')
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [2]:
df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [3]:
df.sample(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
9817,ESLock File Recovery Lite,PRODUCTIVITY,3.0,460,161k,"50,000+",Free,0,Everyone,Productivity,"January 5, 2016",1.5.9,4.0.3 and up
5923,BA Status,TRAVEL_AND_LOCAL,NaN,0,5.1M,100+,Free,0,Everyone,Travel & Local,"August 13, 2016",1.0,4.0.3 and up
10689,Alarm.fo – choose your info,SOCIAL,4.4,19,3.1M,"1,000+",Free,0,Everyone,Social,"May 29, 2018",1.4.8,4.1 and up
8762,Dr. Panda Town,FAMILY,4.0,36578,Varies with device,"1,000,000+",Free,0,Everyone,Education;Pretend Play,"August 3, 2018",Varies with device,Varies with device
288,Fast Scanner : Free PDF Scan,BUSINESS,4.5,103755,14M,"10,000,000+",Free,0,Everyone,Business,"July 11, 2018",3.9.2,4.1 and up

In [4]:
df.Category.unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION',
       '1.9'], dtype=object)

In [5]:
df.Category.nunique()

34

In [6]:
df.Category.value_counts()

Category
FAMILY                 1972
GAME                   1144
TOOLS                   843
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         392
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     231
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
LIBRARIES_AND_DEMO       85
AUTO_AND_VEHICLES        85
WEATHER                  82
ART_AND_DESIGN           65
EVENTS                   64
PARENTING                60
COMICS                   60
BEAUTY                   53
1.9                       1
Name: count, dtype: int64

In [7]:
df.Category.value_counts(normalize=True)

Category
FAMILY                 0.181902
GAME                   0.105525
TOOLS                  0.077760
MEDICAL                0.042708
BUSINESS               0.042432
PRODUCTIVITY           0.039111
PERSONALIZATION        0.036159
COMMUNICATION          0.035698
SPORTS                 0.035421
LIFESTYLE              0.035237
FINANCE                0.033761
HEALTH_AND_FITNESS     0.031455
PHOTOGRAPHY            0.030901
SOCIAL                 0.027212
NEWS_AND_MAGAZINES     0.026105
SHOPPING               0.023983
TRAVEL_AND_LOCAL       0.023799
DATING                 0.021585
BOOKS_AND_REFERENCE    0.021308
VIDEO_PLAYERS          0.016142
EDUCATION              0.014390
ENTERTAINMENT          0.013744
MAPS_AND_NAVIGATION    0.012637
FOOD_AND_DRINK         0.011715
HOUSE_AND_HOME         0.008117
LIBRARIES_AND_DEMO     0.007841
AUTO_AND_VEHICLES      0.007841
WEATHER                0.007564
ART_AND_DESIGN         0.005996
EVENTS                 0.005904
PARENTING              0.005535
COMICS                 0.005535
BEAUTY                 0.004889
1.9                    0.000092
Name: proportion, dtype: float64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [9]:
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [10]:
df.describe(include='O')

,App,Category,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10841,10841,10841,10841,10841,10840,10841,10840,10841,10841,10833,10838
unique,9660,34,6002,462,22,3,93,6,120,1378,2832,33
top,ROBLOX,FAMILY,0,Varies with device,"1,000,000+",Free,0,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1972,596,1695,1579,10039,10040,8714,842,326,1459,2451

In [11]:
df.duplicated().sum()

483

In [12]:
df.drop_duplicates(subset='App', inplace=True)

In [13]:
df.duplicated().sum()

0

In [14]:
df.isna().mean() * 100

App                0.000000
Category           0.000000
Rating            15.144928
Reviews            0.000000
Size               0.000000
Installs           0.000000
Type               0.010352
Price              0.000000
Content Rating     0.010352
Genres             0.000000
Last Updated       0.000000
Current Ver        0.082816
Android Ver        0.031056
dtype: float64

In [15]:
df['Rating']= df['Rating'].fillna(df['Rating'].mean())

In [16]:
df.isna().mean() * 100

App               0.000000
Category          0.000000
Rating            0.000000
Reviews           0.000000
Size              0.000000
Installs          0.000000
Type              0.010352
Price             0.000000
Content Rating    0.010352
Genres            0.000000
Last Updated      0.000000
Current Ver       0.082816
Android Ver       0.031056
dtype: float64

In [17]:
df.dropna(inplace=True)

In [18]:
df.isna().sum().sum()

0

In [19]:
# Pandas Profiling
# from ydata_profiling import ProfileReport
# profile = ProfileReport(df, title='Pandas Profiling Report', html={'style':{'full_width':True}})
# profile.to_file(output_file="playstore.html")

In [20]:
df.describe(include='O')

,App,Category,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,9648,9648,9648,9648,9648,9648,9648,9648,9648,9648,9648,9648
unique,9648,33,5328,457,20,2,92,6,118,1376,2817,33
top,Photo Editor & Candy Camera & Grid & ScrapBook,FAMILY,0,Varies with device,"1,000,000+",Free,0,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,1,1828,591,1226,1416,8895,8895,7893,824,252,1054,2202

In [21]:
# df['Reviews'] = df['Reviews'].astype(int)
df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce')

In [22]:
df['Reviews'].isna().sum()

0

In [23]:
df['Reviews'].dtype

dtype('int64')

In [24]:
df['Size'].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '5.5M', '17M', '39M', '31M',
       '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M', '5.2M',
       '11M', '24M', 'Varies with device', '9.4M', '15M', '10M', '1.2M',
       '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k', '3.6M',
       '5.7M', '8.6M', '2.4M', '27M', '2.7M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '80M', '1.7M', '74M',
       '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M', '71M',
       '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k', '899k',
       '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M', '89M',
       '696k', '544k', '525k', '920k', '779k', '853k', '720k', '713k',
       '772k', '318k', '58k', '241k', '196k', '857k', '51k', '953k',
       '865k', '251k', '930k', '540k', '313k', '746k', '203k', '26k',
       '314k', '239k', '371k', '220k', '730k', '756k', '91k', '293k',
       '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k', '81k',
       '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '219k', '55k', '948k', '323k', '691k',
       '511k', '951k', '963k', '25k', '554k', '351k', '27k', '82k',
       '208k', '913k', '514k', '551k', '29k', '103k', '898k', '743k',
       '116k', '153k', '209k', '353k', '499k', '173k', '597k', '809k',
       '122k', '411k', '400k', '801k', '787k', '50k', '643k', '986k',
       '97k', '516k', '837k', '780k', '961k', '269k', '20k', '498k',
       '600k', '749k', '642k', '881k', '72k', '656k', '601k', '221k',
       '228k', '108k', '940k', '176k', '33k', '663k', '34k', '942k',
       '259k', '164k', '458k', '245k', '629k', '28k', '288k', '775k',
       '785k', '636k', '916k', '994k', '309k', '485k', '914k', '903k',
       '608k', '500k', '54k', '562k', '847k', '957k', '688k', '811k',
       '270k', '48k', '329k', '523k', '921k', '874k', '981k', '784k',
       '280k', '24k', '518k', '754k', '892k', '154k', '860k', '364k',
       '387k', '626k', '161k', '879k', '39k', '970k', '170k', '141k',
       '160k', '144k', '143k', '190k', '376k', '193k', '246k', '73k',
       '992k', '253k', '420k', '404k', '470k', '226k', '240k', '89k',
       '234k', '257k', '861k', '467k', '157k', '44k', '676k', '67k',
       '552k', '885k', '1020k', '582k', '619k'], dtype=object)

In [25]:
def fix_size(size):
    size = size.lower()
    if 'm' in size:
        x = size[:-1]
        x = float(x)
        return x
    elif 'k' in size:
        x = size[:-1]
        x = float(x)
        x = x / 1000
        return x
    else:
        return np.nan

In [26]:
fix_size('Varies with device')

nan

In [27]:
fix_size('13M')

13.0

In [28]:
fix_size('130K')

0.13

In [29]:
df['Size'] = df['Size'].apply(fix_size)

In [30]:
df['Size'].describe()

count    8422.000000
mean       20.413946
std        21.833132
min         0.008500
25%         4.600000
50%        12.000000
75%        28.000000
max       100.000000
Name: Size, dtype: float64

In [31]:
df['Size'].isna().mean()

0.12707296849087893

In [32]:
df.groupby('Category')['Size'].mean()

Category
ART_AND_DESIGN         12.529508
AUTO_AND_VEHICLES      20.037147
BEAUTY                 13.795745
BOOKS_AND_REFERENCE    13.199347
BUSINESS               13.867194
COMICS                 13.794959
COMMUNICATION          11.307430
DATING                 15.661119
EDUCATION              19.057101
ENTERTAINMENT          23.043750
EVENTS                 13.963754
FAMILY                 27.222893
FINANCE                17.368127
FOOD_AND_DRINK         20.494318
GAME                   41.866609
HEALTH_AND_FITNESS     20.669707
HOUSE_AND_HOME         15.970258
LIBRARIES_AND_DEMO     10.735281
LIFESTYLE              14.844916
MAPS_AND_NAVIGATION    16.368121
MEDICAL                19.189399
NEWS_AND_MAGAZINES     12.470189
PARENTING              22.512963
PERSONALIZATION        11.251413
PHOTOGRAPHY            15.666158
PRODUCTIVITY           12.342505
SHOPPING               15.491435
SOCIAL                 15.984090
SPORTS                 24.058361
TOOLS                   8.794674
TRAVEL_AND_LOCAL       24.204410
VIDEO_PLAYERS          15.792756
WEATHER                12.680036
Name: Size, dtype: float64

In [33]:
# Impute missing values according to category
df['Size'] = df.groupby('Category')['Size'].transform(lambda x: x.fillna(x.mean()))

In [34]:
df['Size'].isna().sum()

0

In [35]:
df[df['Size'].isna()]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [36]:
df.dropna(subset=['Size'], inplace=True)

In [37]:
df['Installs'].unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '0+'], dtype=object)

In [38]:
df['Installs'].nunique()

20

In [39]:
def fix_installs(installs):
    installs = installs.replace('+', '')
    installs = installs.replace(',', '')
    installs = int(installs)
    if installs < 1000 :
        return 'Less than 1k'
    elif installs >= 1000 and installs < 100000:
        return '1k-100k'
    elif installs >= 100000 and installs < 1000000:
        return '100k-1M'
    elif installs >= 1000000 and installs < 10000000:
        return '1M-10M'
    elif installs >= 10000000 and installs < 100000000:
        return '10M-100M'
    else:
        return 'More than 100M'

In [40]:
df['Installs'] = df['Installs'].apply(fix_installs)

In [41]:
df['Installs'].value_counts(normalize = True)

Installs
1k-100k           0.295398
1M-10M            0.209681
Less than 1k      0.185323
100k-1M           0.167496
10M-100M          0.118056
More than 100M    0.024046
Name: proportion, dtype: float64

In [42]:
df['Type'].value_counts(normalize=True)

Type
Free    0.921953
Paid    0.078047
Name: proportion, dtype: float64

In [43]:
df.sample(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
8214,DB Tools,FAMILY,4.6,37,3.300000,1k-100k,Free,0,Everyone,Education,"June 17, 2014",1.9,2.2 and up
204,Box,BUSINESS,4.2,159872,13.867194,10M-100M,Free,0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device
7547,"Ruler(cm, inch)",TOOLS,3.4,2889,2.500000,100k-1M,Free,0,Everyone,Tools,"July 27, 2016",1.1.0,2.3 and up
4941,ac remote control,TOOLS,3.7,9514,7.000000,100k-1M,Free,0,Everyone,Tools,"July 11, 2018",acremotecontrol-v7,4.0.3 and up
6889,Allsetra B.V.,BUSINESS,4.1,15,24.000000,1k-100k,Free,0,Everyone,Business,"April 5, 2018",3.1.2,4.3 and up

In [44]:
df['Price'].unique()

array(['0', '$4.99', '$3.99', '$6.99', '$1.49', '$2.99', '$7.99', '$5.99',
       '$3.49', '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49',
       '$10.00', '$24.99', '$11.99', '$79.99', '$16.99', '$14.99',
       '$1.00', '$29.99', '$12.99', '$2.49', '$10.99', '$1.50', '$19.99',
       '$15.99', '$33.99', '$74.99', '$39.99', '$3.95', '$4.49', '$1.70',
       '$8.99', '$2.00', '$3.88', '$25.99', '$399.99', '$17.99',
       '$400.00', '$3.02', '$1.76', '$4.84', '$4.77', '$1.61', '$2.50',
       '$1.59', '$6.49', '$1.29', '$5.00', '$13.99', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$19.90', '$8.49', '$1.75',
       '$14.00', '$4.85', '$46.99', '$109.99', '$154.99', '$3.08',
       '$2.59', '$4.80', '$1.96', '$19.40', '$3.90', '$4.59', '$15.46',
       '$3.04', '$4.29', '$2.60', '$3.28', '$4.60', '$28.99', '$2.95',
       '$2.90', '$1.97', '$200.00', '$89.99', '$2.56', '$30.99', '$3.61',
       '$394.99', '$1.26', '$1.20', '$1.04'], dtype=object)

In [45]:
def fix_price(price):
    price = price.replace('$', '')
    return float(price)

In [46]:
df['Price'] = df['Price'].apply(fix_price)

In [47]:
df['Price'].describe()

count    9648.000000
mean        1.100193
std        16.861727
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       400.000000
Name: Price, dtype: float64

In [48]:
df['Content Rating'].value_counts()

Content Rating
Everyone           7893
Teen               1036
Mature 17+          393
Everyone 10+        321
Adults only 18+       3
Unrated               2
Name: count, dtype: int64

In [49]:
df['Genres'].value_counts()

Genres
Tools                              824
Entertainment                      560
Education                          509
Business                           420
Medical                            395
                                  ...
Art & Design;Pretend Play            1
Lifestyle;Pretend Play               1
Comics;Creativity                    1
Art & Design;Action & Adventure      1
Strategy;Creativity                  1
Name: count, Length: 118, dtype: int64

In [50]:
df['Last Updated'] = pd.to_datetime(df['Last Updated'], dayfirst=True)

In [51]:
df['Last Updated'].min(), df['Last Updated'].max()

(Timestamp('2010-05-21 00:00:00'), Timestamp('2018-08-08 00:00:00'))

In [52]:
df['Last Updated'].dtype

dtype('<M8[ns]')

In [53]:
df['Last Updated']

0       2018-01-07
1       2018-01-15
2       2018-08-01
3       2018-06-08
4       2018-06-20
           ...
10836   2017-07-25
10837   2018-07-06
10838   2017-01-20
10839   2015-01-19
10840   2018-07-25
Name: Last Updated, Length: 9648, dtype: datetime64[ns]

In [54]:
df['Last Updated Year'] = df['Last Updated'].dt.year
# df['Last Updated Month'] = df['Last Updated'].dt.month
# df['Last Updated Day'] = df['Last Updated'].dt.day

In [55]:
df.describe()

,Rating,Reviews,Size,Price,Last Updated,Last Updated Year
count,9648.000000,9.648000e+03,9648.000000,9648.000000,9648,9648.000000
mean,4.173583,2.168369e+05,20.166148,1.100193,2017-10-31 01:00:08.955223808,2017.346186
min,1.000000,0.000000e+00,0.008500,0.000000,2010-05-21 00:00:00,2010.000000
25%,4.000000,2.500000e+01,5.300000,0.000000,2017-08-07 18:00:00,2017.000000
50%,4.200000,9.690000e+02,13.199347,0.000000,2018-05-05 00:00:00,2018.000000
75%,4.500000,2.944925e+04,27.000000,0.000000,2018-07-17 00:00:00,2018.000000
max,5.000000,7.815831e+07,100.000000,400.000000,2018-08-08 00:00:00,2018.000000
std,0.494475,1.832349e+06,20.620049,16.861727,NaN,1.137109

In [56]:
df.describe(include='O')

,App,Category,Installs,Type,Content Rating,Genres,Current Ver,Android Ver
count,9648,9648,9648,9648,9648,9648,9648,9648
unique,9648,33,6,2,6,118,2817,33
top,Photo Editor & Candy Camera & Grid & ScrapBook,FAMILY,1k-100k,Free,Everyone,Tools,Varies with device,4.1 and up
freq,1,1828,2850,8895,7893,824,1054,2202

In [57]:
numerical_cols = df.select_dtypes(exclude='object').columns
categorical_cols = df.select_dtypes(include='object').columns

In [58]:
numerical_cols

Index(['Rating', 'Reviews', 'Size', 'Price', 'Last Updated',
       'Last Updated Year'],
      dtype='object')

In [59]:
numerical_cols = numerical_cols.to_list()
# numerical_cols.remove('Last Updated Year')
numerical_cols.remove('Last Updated')
numerical_cols

['Rating', 'Reviews', 'Size', 'Price', 'Last Updated Year']

In [60]:
categorical_cols

Index(['App', 'Category', 'Installs', 'Type', 'Content Rating', 'Genres',
       'Current Ver', 'Android Ver'],
      dtype='object')

In [61]:
categorical_cols = categorical_cols.to_list()
categorical_cols.remove('Current Ver')
categorical_cols.remove('Android Ver')
categorical_cols.remove('App')
categorical_cols

['Category', 'Installs', 'Type', 'Content Rating', 'Genres']

In [62]:
def univariate_numerical(df, col):
    # Subplot
    fig = make_subplots(rows=1, cols=2)
    # Histogram
    fig.add_trace(go.Histogram(x=df[col]), row=1, col=1)
    # Boxplot
    fig.add_trace(go.Box(x=df[col]), row=1, col=2)
    fig.update_layout(title_text=f'{col}')
    fig.update_layout(showlegend=False)
    fig.show()

In [63]:
def univariate_categorical(df, col):
    fig = px.bar(df[col].value_counts())
    fig.show()

In [64]:
for num_col in numerical_cols:
    univariate_numerical(df, num_col)

In [65]:
for cat_col in categorical_cols:
    univariate_categorical(df, cat_col)

In [66]:
def bivariate_numerical(df, col1, col2):
    fig = px.scatter(df, x=col1, y=col2, title=f'{col1} vs {col2}')
    fig.show()

In [67]:
bivariate_numerical(df, 'Rating', 'Reviews')

In [68]:
# Top 10 categories
fig = px.bar(df['Category'].value_counts(normalize=True).sort_values(ascending=False)[:10]*100,
                title='Top 10 Category Percentage',
                labels={'value':'Perentage', 'index':'Category'}, width=800, height=500)
fig.update_layout(showlegend=False)
# Annotations with white font color
annotations = []
for i, v in enumerate(df['Category'].value_counts(normalize=True).sort_values(ascending=False)[:10]*100):
    annotations.append(dict(x=i, y=v-1, text=str(round(v))+'%', font_size=10, showarrow=False))
fig.update_layout(annotations=annotations)
fig.update_annotations(font_color='white')
fig.show()

In [69]:
# Bottom 10 categories
fig = px.bar(df['Category'].value_counts().sort_values(ascending=False)[-10:],
                title='Bottom 10 Category Count',
                labels={'value':'Count', 'index':'Category'}, width=800, height=500)
fig.update_layout(showlegend=False)
annotations = []
for i, v in enumerate(df['Category'].value_counts().sort_values(ascending=False)[-10:]):
    annotations.append(dict(x=i, y=v+3, text=str(round(v)), font_size=10, showarrow=False))
fig.update_layout(annotations=annotations)
fig.show()

So, We will consider the category only for the analysis, so we will drop the genre column.

In [70]:
# Rating
px.histogram(df, x='Rating', title='Rating Distribution', width=800, height=500, marginal='box')

In [71]:
df[df['Rating'] > 3.2]['Rating'].describe()

count    9157.000000
mean        4.253579
std         0.341687
min         3.300000
25%         4.100000
50%         4.200000
75%         4.500000
max         5.000000
Name: Rating, dtype: float64

In [72]:
# Percentage of apps with rating greater than 3.2
print ('Percentage of apps with rating greater than 3.2: ', round(df[df['Rating'] > 3.2]['Rating'].count()/df['Rating'].count()*100, 2), '%')

Percentage of apps with rating greater than 3.2:  94.91 %

In [73]:
# Rating vs Category
df.groupby('Category')['Rating'].median().sort_values(ascending=False)

Category
ART_AND_DESIGN         4.400000
COMICS                 4.400000
EDUCATION              4.400000
HEALTH_AND_FITNESS     4.400000
PARENTING              4.350000
BOOKS_AND_REFERENCE    4.300000
PERSONALIZATION        4.300000
GAME                   4.300000
EVENTS                 4.250000
AUTO_AND_VEHICLES      4.200000
SPORTS                 4.200000
SOCIAL                 4.200000
SHOPPING               4.200000
PRODUCTIVITY           4.200000
PHOTOGRAPHY            4.200000
MAPS_AND_NAVIGATION    4.200000
WEATHER                4.200000
FOOD_AND_DRINK         4.200000
FINANCE                4.200000
FAMILY                 4.200000
ENTERTAINMENT          4.200000
LIBRARIES_AND_DEMO     4.175052
LIFESTYLE              4.175052
MEDICAL                4.175052
NEWS_AND_MAGAZINES     4.175052
DATING                 4.175052
COMMUNICATION          4.175052
BUSINESS               4.175052
BEAUTY                 4.175052
TOOLS                  4.175052
TRAVEL_AND_LOCAL       4.175052
VIDEO_PLAYERS          4.175052
HOUSE_AND_HOME         4.175052
Name: Rating, dtype: float64

In [74]:
# Rating vs Type
df.groupby('Type')['Rating'].median().sort_values(ascending=False)

Type
Paid    4.3
Free    4.2
Name: Rating, dtype: float64

In [75]:
# Rating vs Content Rating
df.groupby('Content Rating')['Rating'].median().sort_values(ascending=False)

Content Rating
Adults only 18+    4.500000
Everyone 10+       4.300000
Everyone           4.200000
Mature 17+         4.200000
Teen               4.200000
Unrated            4.137526
Name: Rating, dtype: float64

In [76]:
px.histogram(df[df.Type == 'Paid'], x='Price', title='Price Distribution', width=800, height=500, marginal='box')

In [77]:
# Installs
df.Installs.value_counts()

Installs
1k-100k           2850
1M-10M            2023
Less than 1k      1788
100k-1M           1616
10M-100M          1139
More than 100M     232
Name: count, dtype: int64

In [78]:
df.groupby('Installs')['Price'].max().sort_values(ascending=False)

Installs
1k-100k           400.00
100k-1M           399.99
Less than 1k      399.99
10M-100M            6.99
1M-10M              6.99
More than 100M      0.00
Name: Price, dtype: float64

In [79]:
pd.pivot_table(df, index='Installs', values='Price', aggfunc='max')

                 Price
Installs
100k-1M         399.99
10M-100M          6.99
1M-10M            6.99
1k-100k         400.00
Less than 1k    399.99
More than 100M    0.00

In [80]:
pd.pivot_table(df, index='Installs', values='Rating', aggfunc='median')

                  Rating
Installs
100k-1M         4.200000
10M-100M        4.300000
1M-10M          4.300000
1k-100k         4.175052
Less than 1k    4.175052
More than 100M  4.400000

In [81]:
# Rating vs Price
px.scatter(df, x='Price', y='Rating', title='Rating vs Price', width=800, height=500)

In [82]:
px.scatter(df[(df['Price'] < 50 ) & (df['Price']> 0)], x='Price', y='Rating', title='Rating vs Price', width=800, height=500)

In [83]:
# Price vs Category
px.scatter(df[(df['Price'] < 50 ) & (df['Price']> 0)], x='Price', y='Category', title='Price vs Category', width=800, height=500)

In [84]:
px.box(df[(df['Price'] < 50 ) & (df['Price']> 0)], y='Price', x='Category', title='Price vs Category', width=900, height=500)

In [85]:
# Type
df.Type.value_counts()

Type
Free    8895
Paid     753
Name: count, dtype: int64

In [86]:
px.pie(df, names='Type', title='Type Distribution', width=600, height=400)

In [87]:
# Correlation
df.corr(numeric_only=True)

                     Rating   Reviews      Size     Price  Last Updated Year
Rating             1.000000  0.054945  0.055998 -0.019538           0.116994
Reviews            0.054945  1.000000  0.075452 -0.007604           0.058084
Size               0.055998  0.075452  1.000000 -0.021615           0.194629
Price             -0.019538 -0.007604 -0.021615  1.000000          -0.003642
Last Updated Year  0.116994  0.058084  0.194629 -0.003642           1.000000

In [88]:
# Reviews 
df.Reviews = df.Reviews.astype(int)
df.Reviews.describe()

count    9.648000e+03
mean     2.168369e+05
std      1.832349e+06
min      0.000000e+00
25%      2.500000e+01
50%      9.690000e+02
75%      2.944925e+04
max      7.815831e+07
Name: Reviews, dtype: float64

In [89]:
px.histogram(df, x='Reviews', title='Reviews Distribution', width=800, height=500, marginal='box')

In [90]:
# Top 10 apps with most reviews
df.sort_values(by='Reviews', ascending=False)[:10]['App']

2544                                             Facebook
336                                    WhatsApp Messenger
2545                                            Instagram
335              Messenger – Text and Video Chat for Free
1670                                       Clash of Clans
4005              Clean Master- Space Cleaner & Antivirus
1654                                       Subway Surfers
3665                                              YouTube
7536    Security Master - Antivirus, VPN, AppLock, Boo...
1660                                         Clash Royale
Name: App, dtype: object

In [91]:
px.bar(df.nlargest(10, 'Reviews'), x='App', y='Reviews', title='Top 10 apps with most reviews', width=800, height=500)

In [92]:
# Top 10 Free apps with most reviews
df[df['Type'] == 'Free'].nlargest(10, 'Reviews')[['App', 'Reviews']]

                                                    App   Reviews
2544                                           Facebook  78158306
336                                  WhatsApp Messenger  69119316
2545                                          Instagram  66577313
335            Messenger – Text and Video Chat for Free  56642847
1670                                     Clash of Clans  44891723
4005            Clean Master- Space Cleaner & Antivirus  42916526
1654                                     Subway Surfers  27722264
3665                                            YouTube  25655305
7536  Security Master - Antivirus, VPN, AppLock, Boo...  24900999
1660                                       Clash Royale  23133508

In [93]:
# Top 20 Free apps with most rating
df[df['Type'] == 'Free'].nlargest(20, 'Rating')[['App', 'Rating']]

                                             App  Rating
329                 Hojiboy Tojiboyev Life Hacks     5.0
612                American Girls Mobile Numbers     5.0
615                                 Awake Dating     5.0
633                        Spine- The dating app     5.0
636   Girls Live Talk - Free Text and Video Chat     5.0
640                      Online Girls Chat Group     5.0
654              Speeding Joyride & Car Meet App     5.0
1028                            SUMMER SONIC app     5.0
1030                                  Prosperity     5.0
1038                   Mindvalley U Tallinn 2018     5.0
1547                                Eternal life     5.0
2427                                Sway Medical     5.0
2445                              Labs on Demand     5.0
2448  Dermatology Atlas (Colored & Illustrative)     5.0
2450                             Tablet Reminder     5.0
2452                            Galaxies of Hope     5.0
2454                         KBA-EZ Health Guide     5.0
2455                                FoothillsVet     5.0
2457                               PrimeDelivery     5.0
2458                             You're an Anime     5.0

In [94]:
# Top 20 Paid apps with most rating
df[df['Type'] == 'Paid'].nlargest(20, 'Rating')[['App', 'Rating', 'Category', 'Price']]

,App,Rating,Category,Price
2262,Super Hearing Secret Voices Recorder PRO,5.0,MEDICAL,2.99
2271,FHR 5-Tier 2.0,5.0,MEDICAL,2.99
3957,ADS-B Driver,5.0,TOOLS,1.99
4452,P-Home for KLWP,5.0,PERSONALIZATION,0.99
4477,Android P Style Icon Pack,5.0,PERSONALIZATION,0.99
4988,Easy Hotspot Ad Free,5.0,TOOLS,0.99
5237,Hey AJ! It's Saturday!,5.0,BOOKS_AND_REFERENCE,3.99
5246,Hey AJ! It's Bedtime!,5.0,FAMILY,4.99
5260,AJ Gray Dark Icon Pack,5.0,PERSONALIZATION,0.99
5263,AJ Blue Icon Pack,5.0,PERSONALIZATION,0.99
5482,meStudying: AP English Lit,5.0,FAMILY,4.99
5489,AP Art History Flashcards,5.0,FAMILY,29.99
5917,Ra Ga Ba,5.0,GAME,1.49
5966,BC MVA Fines,5.0,BOOKS_AND_REFERENCE,1.75
7100,CA Speakers,5.0,LIFESTYLE,0.99
7204,TI-84 CE Graphing Calculator Manual TI 84,5.0,FAMILY,4.99
7377,CI 174 Gray Icon Pack,5.0,PERSONALIZATION,0.99
7466,211:CK,5.0,GAME,0.99
7477,USMLE Step 2 CK Flashcards,5.0,FAMILY,19.99
8014,Morse Player,5.0,FAMILY,1.99

In [95]:
# Top 10 Paid apps
df.nlargest(10, 'Price')[['App', 'Price']]

                                 App   Price
4367        I'm Rich - Trump Edition  400.00
4197          most expensive app (H)  399.99
4362                      💎 I'm rich  399.99
5351                       I am rich  399.99
5354                  I am Rich Plus  399.99
5356               I Am Rich Premium  399.99
5358                      I am Rich!  399.99
5359              I am rich(premium)  399.99
5362                   I Am Rich Pro  399.99
5364  I am rich (Most expensive app)  399.99

In [96]:
df.to_csv('playstore_cleaned.csv', index=False)